### ISSUE TITLE
How do I specify which version of Java to use?

### ISSUE THREAD

**Issue by jpsacha** [lokkju/github-action-sbt#1]
I would like to run `sbt +test` with Java 11. How do I setup the `github-action-sbt` to do that?

**Comment by lokkju** [comment]
try:
```
- name: SBT action test
  id: sbt
  uses: lokkju/github-action-sbt@11-1.3.0-2.13.0
  with:
    commands: test
    sbt_project_directory: ./test
```

I'll happily take suggestions on better way to implement the various version tags;  One thing I've been thinking about is creating a docker image with multiple java/sbt version all in one, so it versions can be set via env vars
