### ISSUE TITLE
Plugin failure in sbt action

### ISSUE THREAD

**Issue by gzoller** [lokkju/github-action-sbt#2]
I’m getting failures using sbt-coverage.  It’s like the plugins didn’t import when sbt fired.  It all works great locally but always fails as a github Action.

My action yml is this:

```
name: Gregs Scala CI

on: ["push", "pull_request"]

jobs:
  build:
    name: ScalaJack CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.1'
    - name: Run tests
      uses: lokkju/github-action-sbt@master
      with:
        commands: '+ test'
    - name: Generate coverage report
      uses: lokkju/github-action-sbt@master
      with:
        commands: 'clean coverage test coverageReport coverageAggregate'
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_SCALAJACK }}
```

Here’s a clip of the error:

> /github/workspace/build.sbt:3: error: not found: object scoverage
> import scoverage.ScoverageKeys._

This import is in my build.sbt.  My plugins.sbt file lives in my root project directory and specifies the sbt-coverage plugin.

Can the sby action detect and handle sbt plugins?
